//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolFishNS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoolFishNS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~Unknown~.
        /// </summary>
        internal static string BotAuthor {
            get {
                return ResourceManager.GetString("BotAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attach to a process and select a bot base to use..
        /// </summary>
        internal static string BotIsNotReadyError {
            get {
                return ResourceManager.GetString("BotIsNotReadyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_donate_SM {
            get {
                object obj = ResourceManager.GetObject("btn_donate_SM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop Plugin Pulse Thread after 5 seconds...
        /// </summary>
        internal static string FailedToStopPlugins {
            get {
                return ResourceManager.GetString("FailedToStopPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit max time limit. Stopping bot..
        /// </summary>
        internal static string HitTimeLimit {
            get {
                return ResourceManager.GetString("HitTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;Patterns&gt;
        ///  &lt;Pattern desc=&quot;PlayerPointer&quot;
        ///           pattern=&quot;\x55\x8b\xec\xa1\x00\x00\x00\x00\x83\xec\x10\x85\xc0\x75\x00\x8d\x45\xf0\x50\xe8\x00\x00\x00\x00\x68\x00\x00\x00\x00\x68\x00\x00\x00\x00\x8d\x45\xf0\x6a\x10\x50\xe8\x00\x00\x00\x00\x83\xc4\x14\xa3\x00\x00\x00\x00\xc9\xc3&quot;
        ///           mask=&quot;xxxx????xxxxxx?xxxxx????x????x????xxxxxxx????xxxx????xx&quot;&gt;
        ///    &lt;Add value=&quot;4&quot; /&gt;
        ///    &lt;Lea /&gt;
        ///  &lt;/Pattern&gt;
        ///  &lt;Pattern desc=&quot;FrameScript_ExecuteBuffer&quot; pattern=&quot;\x5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Patterns {
            get {
                return ResourceManager.GetString("Patterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=MNTAWFX9F4M7N.
        /// </summary>
        internal static string PaypalLink {
            get {
                return ResourceManager.GetString("PaypalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with plugin: {0}.
        /// </summary>
        internal static string PluginError {
            get {
                return ResourceManager.GetString("PluginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling {0} due to an exception. Developers should catch their own exceptions..
        /// </summary>
        internal static string PluginPulseException {
            get {
                return ResourceManager.GetString("PluginPulseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congrats. You found the secret button..
        /// </summary>
        internal static string SecretBTNMessage {
            get {
                return ResourceManager.GetString("SecretBTNMessage", resourceCulture);
            }
        }
    }
}
